- name: creating ec2 instances
  hosts: localhost
  connection: local
  vars:
   AMI_ID: ami-09c813fb71547fc4f
   sg_id: sg-09ab53948daadc429
   HOSTED_ZONE_ID: Z0239863CO9I6JC85ISR
   domain_name: joindevops.store
   instances:
    - mongodb 
  tasks:
  - name: creating ec2-instances
    amazon.aws.ec2_instance:
        instance_type: t3.micro
        ami_id: "{{AMI_ID}}" # Replace with a valid AMI ID for your region
        
        
        security_group: "{{sg_id}}" # Or the name of your security group
        wait: true
        tags:
          Name: "{{item}}"
        loop: "{{instances}}"  
    register: ec2_info
  - name: printing the output 
    ansible.builtin.debug:
     msg: "{{ec2_info}}"  
     