- name: creating cart
  hosts: cart
  become: yes
  tasks:
  - name: disable nodejs
    ansible.builtin.command: dnf module disable nodejs -y
  - name: enable nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y
  - name: installing nodejs
    ansible.builtin.package:
     name: nodejs 
     state: present
  - name: Create roboshop system user
    ansible.builtin.user:
     name: roboshop
     system: yes
     home: /app
     shell: /sbin/nologin
     comment: "roboshop system user"
     create_home: yes
  - name: Create /app directory
    ansible.builtin.file:
     path: /app
     state: directory
  - name: Download cart artifact
    ansible.builtin.get_url:
     url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
     dest: /tmp/cart.zip  
  - name: Extract cart application
    ansible.builtin.unarchive:
     src: /tmp/cart.zip
     dest: /app
     remote_src: yes     
  - name: Install NodeJS dependencies
    community.general.npm:
     path: /app   
  - name: copying cart.service  
    ansible.builtin.copy:
     src: cart.service
     dest: /etc/systemd/system/cart.service
  - name: Reload systemd manager configuration
    ansible.builtin.systemd:
     daemon_reload: yes
  - name: start and enable catalogue
    ansible.builtin.service:
     name: cart
     state: started
     enabled: yes    