- name: creating shipping
  hosts: shipping
  become: yes
  tasks:
  - name: installing maven
    ansible.builtin.package:
     name: maven
     state: present
  - name: Create roboshop system user
    ansible.builtin.user:
     name: roboshop
     system: yes
     home: /app
     shell: /sbin/nologin
     comment: "roboshop system user"
     create_home: yes
  - name: Create /app directory
    ansible.builtin.file:
     path: /app
     state: directory  
  - name: Download shipping artifact
    ansible.builtin.get_url:
     url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
     dest: /tmp/shipping.zip  
  - name: Extract shipping application
    ansible.builtin.unarchive:
     src: /tmp/shipping.zip
     dest: /app
     remote_src: yes 
  - name: Run Maven clean and package
    ansible.builtin.command: "mvn clean package"
    args:
        chdir: /app
      
  - name: Move the built JAR to the desired location
    ansible.builtin.command: mv /app/target/shipping-1.0.jar /app/shipping.jar
    args:
       creates: /app/shipping.jar   
  - name: copying shipping.service  
    ansible.builtin.copy:
     src: shipping.service
     dest: /etc/systemd/system/shipping.service
  - name: Reload systemd manager configuration
    ansible.builtin.systemd:
     daemon_reload: yes
  - name: start and enable catalogue
    ansible.builtin.service:
     name: shipping
     state: started
     enabled: yes  
  - name: installing mysql           
    ansible.builtin.package:
     name: mysql
     state: present
  - name: loading schema
    ansible.builtin.shell: mysql -h mysql.joindevops.store -uroot -pRoboShop@1 < /app/db/schema.sql  
  - name: creating app user
    ansible.builtin.shell: mysql -h mysql.joindevops.store -uroot -pRoboShop@1 < /app/db/app-user.sql 
  - name: loading master data
    ansible.builtin.shell: mysql -h mysql.joindevops.store -uroot -pRoboShop@1 < /app/db/master-data.sql
  - name: Restart the shipping service
    ansible.builtin.service:
     name: shipping
     state: restarted
    
